### ISSUE TITLE
Existing path?

### ISSUE THREAD

**Issue by stephanie-geoghan** [stephanie-geoghan/CRJ-605-Final-Project#3]
Hi @jacobtnyoung !

I have been trying to run the updated code in R and have been running into issues with the "path" not existing for the excel file. I have tried to move the file, and have tried to change the path, but then I get the error of "OIS" not being recognized. I tried looking in other R support pages, but have had no luck. Any ideas on how to set the path correctly so that the code can all run smoothly? 

Thank you! 

Stephanie

**Comment by jacobtnyoung** [comment]
Hi @stephanie-geoghan and @zelqadah . I was getting this issue also. I am not sure why it is not allowing you to access the file. 

What I did was created a local copy and just referenced that.
